/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'esp_wrapper' 
 * Target:  'main' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "K1986VE9xI.h"

/* Milandr::Device:Startup@2.2.0i */
/* Target microcontroller definition */
#define USE_K1986VE92xI


#endif /* RTE_COMPONENTS_H */
